### PR TITLE
Fix #9. Added description of current arguments to README.md.

### LINKED ISSUE #9: add arguments section to read me
you can now pass arguments to the script, instructions on how to use those need to go in the readme

### PR DESCRIPTION
**Pull request by Ondkloss**
Added description of current arguments to README.md.
Evaluated "default" column, but as it is currently not widely used it seemed superfluous.

### CODE REVIEW

**Comment by amcquade** [comment]
there are two open PRs that add new arguments to the project. I still need to review and merge those, so maybe we should wait on this merge until after those ones are done.

**Comment by Ondkloss** [comment]
@amcquade no problem. Please inform me when/if they have been processed and I can add the additional arguments!

**Comment by Ondkloss** [comment]
@amcquade I've added the --fresh and --include-albums argument descriptions as well. I think that should cover it?

**Comment by amcquade** [comment]
@Ondkloss looks good to me! thanks!

**Pull request merged**
