### PR TITLE
Fix #18 by moving getToken into models.py

### LINKED ISSUE #18: move getToken to appropriate location
The User class was moved in #13 but getToken() remains in `fresh_script.py`.  GetToken needs to be either a member function of the User class or refactored and put in the constructor.

### PR DESCRIPTION
**Pull request by Ondkloss**
Moved `getToken` into model.py and made it a member function of the User class.
Fixed a comment type-o. Removed a legacy `getToken` call comment.

### CODE REVIEW

**Comment by amcquade** [comment]
awesome. has this been tested? @Ondkloss

**Comment by Ondkloss** [comment]
@amcquade it has been tested in production by myself. Anything more sensible in mind?
Thanks for the neat little project!

**Comment by amcquade** [comment]
@Ondkloss Great! Not that i can think of right now, a PR broke the project so i really wanted to get that fixed. Thanks for the contribution!

**Comment by Ondkloss** [comment]
Thanks for the merge. Is there anything else I can look into, or are you leaving them open for new contributors, @amcquade?

**Pull request merged**
